version: '3.2'
services:
  pizza-backend:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
  pizza-frontend:
    image: mwilmanbag/pizza-angular-exercise:v2
    ports:
      - "4200:80"
